INSERT INTO `customers` (`firstName`, `lastName`, `username`, `password`) VALUES ('jordan', 'harrison', 'JHarry', 'pass323');
INSERT INTO `customers` (`firstName`, `lastName`, `username`, `password`) VALUES ('jordan', 'harrison', 'JHarry', 'pass323');
INSERT INTO `customers` (`firstName`, `lastName`, `username`, `password`) VALUES ('jordan', 'harrison', 'JHarry', 'pass323');
INSERT INTO `customers` (`firstName`, `lastName`, `username`, `password`) VALUES ('jordan', 'harrison', 'JHarry', 'pass323');
INSERT INTO `customers` (`firstName`, `lastName`, `username`, `password`) VALUES ('jordan', 'harrison', 'JHarry', 'pass323');
INSERT INTO `items` (`cost`, `name`) VALUES (4.35, 'testitem');
INSERT INTO `items` (`cost`, `name`) VALUES (4.35, 'testitem');
INSERT INTO `items` (`cost`, `name`) VALUES (4.35, 'testitem');
INSERT INTO `items` (`cost`, `name`) VALUES (4.35, 'testitem');
INSERT INTO `items` (`cost`, `name`) VALUES (4.35, 'testitem');
INSERT INTO `orders` (`customerid`, `cost`)  VALUES (1, 12.21);
